### PR TITLE
Sd add asset tag example repro

### PR DESCRIPTION
**Pull request by thejchap**

### CODE REVIEW

**Comment by thejchap** [comment]
https://github.com/thoughtbot/ember-cli-rails/issues/298

**Comment by seanpdoyle** [comment]
@thejchap I'm sorry, I don't understand these proposed changes.

I attempted to configure the project similarly to what you [described here](https://github.com/thoughtbot/ember-cli-rails/issues/298#issue-118287306), including `config.assets.prefix = '/staging/assets'`.

I then proposed that you finish bridging the gap between this project and yours:

> Could you pull that down, make it work more like your production app in whatever way you need to?

Could you elaborate on why the contents of this PR reverse my changes? Does your project no longer set the `config.assets.prefix`?

**Comment by thejchap** [comment]
@seanpdoyle yeah- I tried to get the app to the simplest config possible where the bug is still consistently reproducible to eliminate moving parts. Check my comment in the issue thread for the link to the heroku app that demonstrates the behavior even with this config (no custom asset host/prefix/etc)

Anyways, the behavior is still present even w/o these changes

**Comment by thejchap** [comment]
@seanpdoyle maybe worded better- in opening up and running/deploying this app I discovered that the bug was reproducible even without any custom config/prefix/etc....meaning it may not be tied to that after all. Just thought it might be helpful to demonstrate

**Pull request closed without merging**
